### ISSUE TITLE
Overall project 

### ISSUE THREAD

**Issue by lsh4205** [lsh4205/ROS_backend#4]
Hello, I have completed backend technical assignment. However, I'm wondering everything is on the right track, such as file formats, file name formats, and directory formats. In order to ensure accuracy and compliance with the required standards, I would greatly appreciate your professional guidance and feedback. @jungsu-kwon

**Comment by jungsu-kwon** [comment]
@lsh4205 first I would like to thank you for finishing assignment. 

I hope you enjoyed building the application.

I liked your submission and will proceed you to second interview.

However, I will ask you following question which you will have some time

to think upon (if you have some time maybe you can directly make a commit to this repo)

```
what optimisation can be introduced to implemented solution 
if data is not a rosbag but live stream rostopic
```

Overall I liked your solution and you will get an email from tony 
how you can proceed to next step by 16th of May (KST)

Jungsu
